---
- name: Ensure all required packages are installed
  yum:
    name: '{{ packages }}'
    state: present
    update_cache: yes
  vars:
    packages:
      - python-psycopg2
      - postgresql-server

- name: Init PostgreSQL DB if needed
  command: postgresql-setup initdb
  args:
    creates: "{{ POSTGRESQL_DATA_DIRECTORY }}/PG_VERSION"

- name: Ensure pg_hba.conf file is up-to-date
  template:
    src: pg_hba.conf.j2
    dest: '{{ POSTGRESQL_DATA_DIRECTORY }}/pg_hba.conf'
    owner: postgres
    group: postgres
    mode: 0640
  notify: restart postgresql

- name: Ensure postgresql.conf is up-to-date
  lineinfile:
    dest: '{{ POSTGRESQL_DATA_DIRECTORY }}/postgresql.conf'
    regexp: '^#?{{ item.option }}.+$'
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
  loop: '{{ POSTGRESQL_CONFIG_OPTIONS }}'
  notify: restart postgresql

  # To ensure that later tasks can connect to the database flush handlers here to restart postgresql
- meta: flush_handlers

- name: Ensure PostgreSQL is running and enabled
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure database users exist
  become: yes
  become_user: postgres
  postgresql_user:
    name: '{{ item.name }}'
    password: '{{ item.password }}'
  with_items: '{{ POSTGRESQL_USERS }}'

- name: Ensure databases exist
  become: yes
  become_user: postgres
  postgresql_db:
    name: '{{ item.name }}'
    owner: '{{ item.owner }}'
  with_items: '{{ POSTGRESQL_DATABASES }}'